name: Main

on: [workflow_dispatch]

jobs:
  job_1:
    strategy:
      matrix:
        os_version: [macos-latest, ubuntu-latest]
        node_version: [10, 12, 14]
        
    name: My first job
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v3.6
        with:
          node-version: ${{ matrix.node_version }}
