

jobs:
  job_1:
    runs-on: ubuntu-latest
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]

 
on: [workflow_dispatch]
 
name: Main
