name: Main

on: [workflow_dispatch, pull_request, pull_request_target]

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Access secres
        run: |
          echo "Secret: [${{ secrets.CONNECTION_STRING }}]"
          echo "Var: [${{ vars.MY_VAR }}]"
      - name: Write messages to the log
        run: |
          echo "::debug::This is a debug message"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=.github/workflows/main.yml,line=17,col=10,endColumn=37::Error in main.yml workflow"
          
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret='123456'
          echo "::add-mask::$the_secret"
          echo "$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
          echo "${{ steps.sets-a-secret.outputs.secret-number }}" | sed 's/./& /g'

