name: My First Workflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu
    
    steps:
      - run: echo "👋 Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v3.5.2 
      
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains th efollowing files:"
          tree
